### ISSUE TITLE
Using auto-update

### ISSUE THREAD

**Issue by kazu-yamamoto** [khibino/dns-resolver#11]
`UpdateCache` uses `threadDelay`. The dedicated process always wakes up every second even if no query is requested. We should use `Control.AutoUpdate` in `auto-update` to solve this issue.

**Comment by khibino** [comment]
Control.AutoUpdate simply uses threadDelay, so replacing it does not seem to change the situation.

https://hackage.haskell.org/package/auto-update-0.1.6/docs/src/Control.AutoUpdate.html#mkAutoUpdate


Wouldn't it be more important to calculate the time to sleep so that it is more efficient?

**Comment by kazu-yamamoto** [comment]
- Control.AutoUpdate for TimeCache
- Control.Reaper for UpdateCache

**Comment by khibino** [comment]
- Control.AutoUpdate for TimeCache resolved by #16

**Comment by kazu-yamamoto** [comment]
Closing.
